<?php /* Smarty version 2.6.31, created on 2020-06-12 19:06:57
         compiled from crts/form.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'lbl', 'crts/form.tpl', 8, false),array('block', 'select', 'crts/form.tpl', 9, false),array('block', 'glink', 'crts/form.tpl', 226, false),array('function', 'input', 'crts/form.tpl', 8, false),array('function', 'area', 'crts/form.tpl', 35, false),array('function', 'hidden', 'crts/form.tpl', 218, false),)), $this); ?>
﻿<?php echo $this->_tpl_vars['Form']->create('Crt'); ?>
                                                                                                                                  
<div id="stylized" class="myform" style="width:820px;">                                                                                                 
                                                                                                                                                        
<h1>C R T</h1>                                                                                                                                          
<p>Carta de Porte Internacional por Carretera</p>                                                                                                       
                                                                                                                                                        
<table>                                                                                                                                                 
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Fecha<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>        </td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'fecha','size' => '10'), $this);?>
</td></tr>                                                                      
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Tipo de Operaci&oacute;n<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>        </td><td><?php $this->_tag_stack[] = array('select', array('name' => 'tipo_operacion','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>|,Exportaci&oacute;n|E,Importaci&oacute;n|I<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Valor del flete<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>        </td><td><table><tr>                                                                                          
                                                   <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_valor_flete','size' => '12','style' => "text-align:right"), $this);?>
</td>                          
                                                   <td>&nbsp;<?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Moneda<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>&nbsp;</td>                                                               
                                                   <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_mon_flete','size' => '3'), $this);?>
</td>                                                      
                                                   </tr>                                                                                                
                                                   </table>                                                                                             
                                               </td>                                                                                                    
</tr>                                                                                                                                                   
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Cliente      <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'cliente_id','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>      <?php echo $this->_tpl_vars['clientes']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>                                                 
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Destinatario <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'destinatario_id','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?> <?php echo $this->_tpl_vars['clientes']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>                                                 
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Consignatario<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'consignatario_id','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['clientes']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr> 
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Facturar a<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'facturar_id','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['clientes']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>          
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Factura<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('name' => 'crts_factura','size' => '20','class' => 'smallFont'), $this);?>
</td></tr>   
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Gu&iacute;a Cliente<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('name' => 'crts_guia_cliente','size' => '20','class' => 'smallFont'), $this);?>
</td></tr>      
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Gu&iacute;a Aduanera<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('name' => 'crts_guia_aduanera','size' => '20','class' => 'smallFont'), $this);?>
</td></tr>      
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Desde<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('name' => 'crts_desde','size' => '24','class' => 'smallFont'), $this);?>
</td></tr>   
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Hasta<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('name' => 'crts_hasta','size' => '24','class' => 'smallFont'), $this);?>
</td></tr>   
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Es Facturable<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'crts_facturable','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>|,S&iacute;|S,No|N<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>                                            
<tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Estado<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php $this->_tag_stack[] = array('select', array('name' => 'crts_estado','class' => 'smallFont')); $_block_repeat=true;smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>|,Ingresado|I,Cerrado|C<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_select($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td></tr>                                                 
                                                                                                                                                        
</table>                                                                                                                                                
<div style="float:left; width: 820px; height: 400px; border: 1px solid black;">                                                                         
    <div style="float:left; width: 450px; height: 398px; border-right: 1px solid black;">                                                               
        <div style="float:left; width: 448px; height: 100px;border-bottom: 1px solid black;">                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>1. Nombre y domicilio del remitente<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                              
            <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_nombre_domicilio1','rows' => '4','cols' => '50'), $this);?>
                                                                                         
        </div>                                                                                                                                          
         <div style="float:left; width: 448px; height: 100px;border-bottom: 1px solid black;">                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>4. Nombre y domicilio del destinatario<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                           
            <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_nom_dom_destin','rows' => '4','cols' => '50'), $this);?>
                                                                                            
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 100px;border-bottom: 1px solid black;">                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>6. Nombre y domicilio del consignatario<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                          
            <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_nom_dom_consig','rows' => '4','cols' => '50'), $this);?>
                                                                                            
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 100px;">                                                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>9. Notificar a<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                                   
            <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_notificar_a','rows' => '4','cols' => '50'), $this);?>
                                                                                               
        </div>                                                                                                                                          
    </div>                                                                                                                                              
                                                                                                                                                        
    <div style="float:left; width: 364px; height: 390px;">                                                                                              
        <div style="float:left; width: 370px; height: 28px; border-bottom: 1px solid black;">                                                           
            <table>                                                                                                                                     
            <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>2. Número<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_numero','size' => '20'), $this);?>
</td></tr>                                                         
            </table>                                                                                                                                    
        </div>                                                                                                                                          
        <div style="float:left; width: 370px; height: 100px; border-bottom: 1px solid black;">                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&nbsp;3. Nombre y domicilio del transportador<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                    
            <?php echo smarty_function_area(array('name' => 'crts_nom_dom_transp','rows' => 5,'cols' => 47,'readonly' => 'true','class' => 'sololectura smallFont'), $this);?>
                                                       
        </div>                                                                                                                                          
        <div style="float:left; width: 370px; height: 40px; border-bottom: 1px solid black;">                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&nbsp;5. Lugar y país de emisión<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                 
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_lug_pais_emis','size' => '45','maxlength' => '50'), $this);?>
                                                                                  
        </div>                                                                                                                                          
         <div style="float:left; width: 370px; height: 58px; border-bottom: 1px solid black;">                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&nbsp;7. Lugar, país y fecha en que el portador se hace cargo de las mercancías<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                  
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_lug_pais_fec','size' => '45','maxlength' => '50'), $this);?>
                                                                                   
        </div>                                                                                                                                          
         <div style="float:left; width: 370px; height: 42px; border-bottom: 1px solid black;">                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&nbsp;8. Lugar, país y plazo de entrega<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                          
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_lug_pais_plaz','size' => '45','maxlength' => '50'), $this);?>
                                                                                  
        </div>                                                                                                                                          
         <div style="float:left; width: 370px; height: 42px; border-bottom: 1px solid black;">                                                          
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&nbsp;10. Portadores sucesivos<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                   
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_port_sucesivos','size' => '45','maxlength' => '50'), $this);?>
                                                                                 
        </div>                                                                                                                                          
    </div>                                                                                                                                              
                                                                                                                                                        
</div>                                                                                                                                                  
                                                                                                                                                        
<div style="float:left; width: 820px; height: 272px; border-left: 1px solid black;border-right: 1px solid black;border-bottom: 1px solid black;">       
    <div style="float:left; width: 450px; height: 270px; border-right: 1px solid black;">                                                               
        <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>11. Cantidad y clase de bultos, marcas y números, tipo de mercancías, contenedores y accesorios<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                      
        <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_cant_clase_bultos','rows' => 13,'cols' => 52), $this);?>
                                                                          
    </div>                                                                                                                                              
    <div style="float:left; width: 264px; height: 220px;">                                                                                              
        <div style="float:left; width: 370px; height: 80px;border-bottom: 1px solid black;">                                                            
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>12. Pesos brutos en Kg.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                          
            <table>                                                                                                                                     
                <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>P.B.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_peso_brut_kg','size' => '11'), $this);?>
</td></tr>                                                     
                <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>P.N.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_peso_neto_kg','size' => '11'), $this);?>
</td></tr>                                                     
            </table>                                                                                                                                    
        </div>                                                                                                                                         
        <div style="float:left; width: 370px; height: 45px;border-bottom: 1px solid black;">                                                            
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>13. Volumen en m.cu.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                             
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_vol_m3','size' => '14'), $this);?>
                                                                                             
        </div>                                                                                                                                          
                                                                                                                                                        
        <div style="float:left; width: 370px; height: 45px;">                                                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>14. Valor<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                                        
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_valor','size' => '20'), $this);?>
                                                                                             
        </div>                                                                                                                                          
        <div style="float:left; width: 370px; height: 45px;">                                                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Moneda<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                                           
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_moneda','size' => '3'), $this);?>
                                                                                              
        </div>                                                                                                                                          
    </div>                                                                                                                                              
</div>                                                                                                                                                  
                                                                                                                                                        
<div style="float:left; width: 820px; height: 500px; border: 1px solid black;">                                                                         
    <div style="float:left; width: 450px; height: 500px; border-right: 1px solid black;">                                                               
                                                                                                                                                        
       <div style="float:left; width: 358px; height: 186px;border-bottom: 1px solid black;">                                                            
           <table border="1">                                                                                                                           
              <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>15. Gastos a pagar<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                
                  <td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Monto remitente<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                   
                  <td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Moneda<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                            
                  <td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Monto destinat.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                   
                  <td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Moneda<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                            
              </tr>                                                                                                                                     
              <tr><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_flete','size' => '18','maxlength' => '17'), $this);?>
</td>                                                                           
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_flete_monto','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                           
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_flete_moneda','size' => '3'), $this);?>
</td>                                                                                    
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_dest_flete','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                           
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_f_dest_moneda','size' => '3'), $this);?>
</td>                                                                                  
              </tr>                                                                                                                                     
              <tr><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_seguro','size' => '18','maxlength' => '17'), $this);?>
</td>                                                                          
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_seguro_monto','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                          
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_seguro_moneda','size' => '3'), $this);?>
</td>                                                                                   
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_dest_seguro','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                          
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_s_dest_moneda','size' => '3'), $this);?>
</td>                                                                                  
              </tr>                                                                                                                                     
              <tr><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_otro','size' => '18','maxlength' => '17'), $this);?>
</td>                                                                            
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_otro_monto','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                          
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_otro_moneda','size' => '3'), $this);?>
</td>                                                                                   
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_dest_otro','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                          
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_o_dest_moneda','size' => '3'), $this);?>
</td>                                                                                   
              </tr>                                                                                                                                     
              <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>TOTAL<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td>                                                                                                             
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_otro_monto_total','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                    
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_otro_moneda_total','size' => '3'), $this);?>
</td>                                                                             
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_dest_otro_total','size' => '8','style' => "text-align:right"), $this);?>
</td>                                                    
                  <td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_o_dest_moneda_total','size' => '3'), $this);?>
</td>                                                                             
              </tr>                                                                                                                                     
           </table>                                                                                                                                     
       </div>                                                                                                                                           
       <div style="float:left; width: 448px; height: 56px;border-bottom: 1px solid black;">                                                             
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>19. Monto del flete externo<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                      
            <table>                                                                                                                                     
                <tr><td>US$</td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_monto_flete_ext','size' => '14'), $this);?>
</td></tr>                                                           
            </table>                                                                                                                                    
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 46px;border-bottom: 1px solid black;">                                                            
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>20. Monto del reembolso contra entrega<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                           
            <table>                                                                                                                                     
                <tr><td>US$</td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_monto_reembolso','size' => '14'), $this);?>
</td></tr>                                                           
            </table>                                                                                                                                    
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 56px;">                                                                                           
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>21. Nombre y firma del remitente o su representante<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                              
            <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_nom_firma_remit','size' => '45','maxlength' => '60'), $this);?>
                                                                              
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 30px;">                                                                                           
            <table>                                                                                                                                     
                <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Fecha<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_nom_firma_rfec','size' => '10'), $this);?>
</td></tr>                                               
            </table>                                                                                                                                    
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 56px; border-top:1px solid black;">                                                               
            <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>23. Nombre, firma y sello del portador<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                           
            <?php echo smarty_function_input(array('class' => 'sololectura','name' => 'crts_nom_firma_sello','size' => '45','maxlength' => '60','readonly' => 'true'), $this);?>
                                                                              
        </div>                                                                                                                                          
        <div style="float:left; width: 448px; height: 30px;">                                                                                           
            <table>                                                                                                                                     
                <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Fecha<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_nom_firma_sfec','size' => '10'), $this);?>
</td></tr>                                               
            </table>                                                                                                                                    
        </div>                                                                                                                                          
    </div>                                                                                                                                              
                                                                                                                                                        
    <div style="float:left; width: 350px; height: 300px;">                                                                                              
                                                                                                                                                        
         <div style="float:left; width: 348px; height: 100px; border-bottom:1px solid black;">                                                          
           <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>16. Declaración del valor de las mercancias<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                       
           <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_decl_valor','rows' => '4','cols' => '40'), $this);?>
                                                                                            
                                                                                                                                                        
       </div>                                                                                                                                           
       <div style="float:left; width: 348px; height: 100px; border-bottom:1px solid black;">                                                            
           <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>17. Documentos anexos<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                             
           <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_docto_anexo','rows' => '4','cols' => '40'), $this);?>
                                                                                           
                                                                                                                                                        
       </div>                                                                                                                                           
        <div style="float:left; width: 348px; height: 100px; border-bottom:1px solid black;">                                                           
           <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>18. Instrucciones sobre formalidades de aduana<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                    
           <?php echo smarty_function_area(array('class' => 'courierFont','name' => 'crts_inst_formal','rows' => '4','cols' => '40'), $this);?>
                                                                                           
                                                                                                                                                        
       </div>                                                                                                                                           
       <div style="float:left; width: 348px; height: 100px;">                                                                                           
           <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>22. Declaraciones y observaciones<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                 
           <?php echo smarty_function_area(array('name' => 'crts_decl_observ','rows' => '5','cols' => '48','readonly' => 'true','class' => 'sololectura smallFont'), $this);?>
                                                       
                                                                                                                                                        
       </div>                                                                                                                                           
       <div style="float:left; width: 348px; height: 60px;border-top:1px solid black;">                                                                 
           <?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>24. Nombre y firma del destinatario o su representante<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                            
           <?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_nom_firma_des','size' => '45','maxlength' => '60'), $this);?>
                                                                                 
                                                                                                                                                        
       </div>                                                                                                                                           
       <div style="float:left; width: 348px; height: 30px;">                                                                                            
            <table>                                                                                                                                     
                <tr><td><?php $this->_tag_stack[] = array('lbl', array()); $_block_repeat=true;smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Fecha<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lbl($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></td><td><?php echo smarty_function_input(array('class' => 'smallFont','name' => 'crts_nom_firma_sdes','size' => '10'), $this);?>
</td></tr>                                               
            </table>                                                                                                                                    
        </div>                                                                                                                                          
                                                                                                                                                        
    </div>                                                                                                                                              
                                                                                                                                                        
</div>                                                                                                                                                  
<table>                                                                                                                                                 
   <tr><td colspan="2" align="right"><button type="submit">Grabar</button></td></tr>                                                                    
</table>                                                                                                                                                
<?php echo smarty_function_hidden(array('name' => 'id'), $this);?>
                                                                                                                                      
<?php echo smarty_function_hidden(array('name' => 'fec_carga'), $this);?>
                                                                                                                               
<?php echo smarty_function_hidden(array('name' => 'fec_descarga'), $this);?>
                                                                                                                            
<?php echo smarty_function_hidden(array('name' => 'factura_crt'), $this);?>
                                                                                                                             
<?php echo smarty_function_hidden(array('name' => 'factura_dias'), $this);?>
                                                                                                                            
<?php echo smarty_function_hidden(array('name' => 'estado'), $this);?>
                                                                                                                                  
                                                                                                                                                        
<br>                                                                                                                                                    
<?php $this->_tag_stack[] = array('glink', array('caption' => 'Volver','action' => 'index')); $_block_repeat=true;smarty_block_glink($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_glink($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>                                                                                                         
<div class="spacer"></div>                                                                                                                              
                                                                                                                                                        
<?php echo '                                                                                                                                               
<script language="javascript">                                                                                                                          
$("#cliente_id").change(function(){                                                                                                                     
  cliente_id = $("#cliente_id").val();                                                                                                                  
                                                                                                                                                        
  //alert("cliente: "+cliente_id);                                                                                                                      
                                                                                                                                                        
  $.ajax({url:"http://www.ruta-chile.com/rutas/crts/getCliente/"+cliente_id,success:function(result){                                                   
    //$("#div1").html(result);                                                                                                                          
                                                                                                                                                        
    l = result.split("@@");                                                                                                                             
                                                                                                                                                        
    //alert(l[0]);                                                                                                                                      
    document.getElementById("crts_nombre_domicilio1").value=l[0].trim();                                                                                
  }});                                                                                                                                                  
});                                                                                                                                                     
                                                                                                                                                        
$("#destinatario_id").change(function(){                                                                                                                
  destinatario_id = $("#destinatario_id").val();                                                                                                        
                                                                                                                                                        
  $.ajax({url:"http://www.ruta-chile.com/rutas/crts/getCliente/"+destinatario_id,success:function(result){                                              
    //$("#div1").html(result);                                                                                                                          
                                                                                                                                                        
    l = result.split("@@");                                                                                                                             
                                                                                                                                                        
    //alert(l[0]);                                                                                                                                      
    document.getElementById("crts_nom_dom_destin").value=l[0].trim();                                                                                   
  }});                                                                                                                                                  
});                                                                                                                                                     
                                                                                                                                                        
$("#consignatario_id").change(function(){                                                                                                               
  consignatario_id = $("#consignatario_id").val();                                                                                                      
                                                                                                                                                        
  $.ajax({url:"http://www.ruta-chile.com/rutas/crts/getCliente/"+consignatario_id,success:function(result){                                             
    //$("#div1").html(result);                                                                                                                          
                                                                                                                                                        
    l = result.split("@@");                                                                                                                             
                                                                                                                                                        
    //alert(l[0]);                                                                                                                                      
    document.getElementById("crts_nom_dom_consig").value=l[0].trim();                                                                                   
    document.getElementById("crts_notificar_a").value=l[0].trim();                                                                                      
                                                                                                                                                        
                                                                                                                                                        
  }});                                                                                                                                                  
});                                                                                                                                                     
</script>                                                                                                                                               
'; ?>
                                                                                                                                              
</form>                                                                                                                                                 
</div>                                                                                                                                                  
                                                                                                                                                        
                                                                                                                                                        